version: '0'
name: 'react-deno-mongo'
services:
  react:
    build:
      context: ./react-frontend #move to the root of folder struct
      dockerfile: Dockerfile
    image: react-frontend-image
    container_name: react-frontend-container
    volumes:
       - ./react-frontend:/usr/src/app/react-frontend
       - /usr/src/app/react-frontend/node_modules
    ports:
      - '3000:3000' #for docker to know where to redirect hot module reload queries
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  deno:
    user: "deno"
    build:
      context: ./deno-backend
      dockerfile: Dockerfile
    image: deno-image
    container_name: deno-container
    volumes: 
      - ./deno-backend:/app
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    expose:
    - "8000"
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo:
